## RESTAURANT FOOD COST
* TITLE: The feature of the restaurant which can help identify what and for whom it is suitable for.
* RESTAURANT_ID: A unique ID for each restaurant.
* CUISINES: The variety of cuisines that the restaurant offers.
* TIME: The open hours of the restaurant.
* CITY: The city in which the restaurant is located.
* LOCALITY: The locality of the restaurant.
* RATING: The average rating of the restaurant by customers.
* VOTES: The overall votes received by the restaurant.
* COST: The average cost of a two-person meal.

In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [68]:
df_train = pd.read_excel('D:/STUDIES/DATA TRAINED/DATASETS/Data-Science-ML-Capstone-Projects-master/Restaurant_food_cost/Participants_Data_Final/Data_Train.xlsx')
df_train

,TITLE,RESTAURANT_ID,CUISINES,TIME,CITY,LOCALITY,RATING,VOTES,COST
0,CASUAL DINING,9438,"Malwani, Goan, North Indian","11am – 4pm, 7:30pm – 11:30pm (Mon-Sun)",Thane,Dombivali East,3.6,49 votes,1200
1,"CASUAL DINING,BAR",13198,"Asian, Modern Indian, Japanese",6pm – 11pm (Mon-Sun),Chennai,Ramapuram,4.2,30 votes,1500
2,CASUAL DINING,10915,"North Indian, Chinese, Biryani, Hyderabadi","11am – 3:30pm, 7pm – 11pm (Mon-Sun)",Chennai,Saligramam,3.8,221 votes,800
3,QUICK BITES,6346,"Tibetan, Chinese",11:30am – 1am (Mon-Sun),Mumbai,Bandra West,4.1,24 votes,800
4,DESSERT PARLOR,15387,Desserts,11am – 1am (Mon-Sun),Mumbai,Lower Parel,3.8,165 votes,300
...,...,...,...,...,...,...,...,...,...
12685,QUICK BITES,13228,"North Indian, Burger, Kebab","12noon – 12midnight (Mon, Tue, Wed, Thu, Sun)...",Hyderabad,Gachibowli,3.8,546 votes,500
12686,"CASUAL DINING,BAR",9686,"Goan, Continental","12noon – 1am (Mon-Fri),11am – 5pm, 7pm – 1am...",Mumbai,Bandra Kurla Complex,4.3,1214 votes,1800
12687,LOUNGE,11133,"Finger Food, Continental, Asian, Chinese",12noon – 12:30AM (Mon-Sun),Navi Mumbai,Vashi,4.0,608 votes,1300
12688,CASUAL DINING,6134,"North Indian, South Indian, Chinese, Street Food",6am – 10:45pm (Mon-Sun),Chennai,Maduravoyal,3.5,32 votes,400
12689,CASUAL DINING,6430,"North Indian, Chinese",12:30pm – 11pm (Mon-Sun),Hyderabad,Vanasthalipuram,3.4,677 votes,600

In [69]:
df_test = pd.read_excel('D:/STUDIES/DATA TRAINED/DATASETS/Data-Science-ML-Capstone-Projects-master/Restaurant_food_cost/Participants_Data_Final/Data_Test.xlsx')
df_test

,TITLE,RESTAURANT_ID,CUISINES,TIME,CITY,LOCALITY,RATING,VOTES
0,CASUAL DINING,4085,"North Indian, Chinese, Mughlai, Kebab",12noon – 12midnight (Mon-Sun),Noida,Sector 18,4.3,564 votes
1,QUICK BITES,12680,"South Indian, Fast Food, Pizza, North Indian",7am – 12:30AM (Mon-Sun),Mumbai,Grant Road,4.2,61 votes
2,CASUAL DINING,1411,"North Indian, Seafood, Biryani, Chinese",11am – 11:30pm (Mon-Sun),Mumbai,Marine Lines,3.8,350 votes
3,None,204,Biryani,"9am – 10pm (Mon, Wed, Thu, Fri, Sat, Sun), 10:...",Faridabad,NIT,3.8,1445 votes
4,QUICK BITES,13453,"South Indian, Kerala",11am – 10pm (Mon-Sun),Kochi,Kaloor,3.6,23 votes
...,...,...,...,...,...,...,...,...
4226,CASUAL DINING,9057,"North Indian, Mughlai, Chinese",11:30am – 11:30pm (Mon-Sun),New Delhi,Punjabi Bagh,3.9,287 votes
4227,None,1247,"Biryani, North Indian, Sandwich, Salad, Wraps",11am – 1am (Mon-Sun),Bangalore,HSR Layout,4.3,469 votes
4228,QUICK BITES,8617,"Continental, North Indian",9:30am – 10:30pm (Mon-Sun),Faridabad,Sector 86,3.7,53 votes
4229,QUICK BITES,6485,"Rolls, Beverages","11am – 11:30pm (Mon, Tue, Wed, Thu, Sat, Sun),...",Kochi,Kochi,-,NaN
4230,QUICK BITES,2421,Mughlai,5pm – 1am (Mon-Sun),Bandra West,Perry Cross Road,3.7,63 votes

In [70]:
df_train.describe(include='all')

,TITLE,RESTAURANT_ID,CUISINES,TIME,CITY,LOCALITY,RATING,VOTES,COST
count,12690,12690.000000,12690,12690,12578,12592,12688,11486,12690.000000
unique,113,NaN,4155,2689,359,1416,32,1847,NaN
top,QUICK BITES,NaN,South Indian,11am – 11pm (Mon-Sun),Chennai,Gachibowli,3.9,44 votes,NaN
freq,4218,NaN,532,1415,2174,166,1238,71,NaN
mean,NaN,7759.134121,NaN,NaN,NaN,NaN,NaN,NaN,655.252246
std,NaN,4504.874150,NaN,NaN,NaN,NaN,NaN,NaN,627.003540
min,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,20.000000
25%,NaN,3863.250000,NaN,NaN,NaN,NaN,NaN,NaN,300.000000
50%,NaN,7740.000000,NaN,NaN,NaN,NaN,NaN,NaN,500.000000
75%,NaN,11688.750000,NaN,NaN,NaN,NaN,NaN,NaN,800.000000
max,NaN,15573.000000,NaN,NaN,NaN,NaN,NaN,NaN,14000.000000

* Most restaurants are open from Monday to Sunday - 11am to 11pm
* Cost varies from Rs.20 to Rs.1400
* South Indian is the most common cuisine

In [71]:
df_train.isnull().sum()

TITLE               0
RESTAURANT_ID       0
CUISINES            0
TIME                0
CITY              112
LOCALITY           98
RATING              2
VOTES            1204
COST                0
dtype: int64

In [72]:
df_test.isnull().sum()

TITLE              0
RESTAURANT_ID      0
CUISINES           0
TIME               0
CITY              35
LOCALITY          30
RATING             2
VOTES            402
dtype: int64

In [73]:
df_train[df_train['CITY'].isnull()]

,TITLE,RESTAURANT_ID,CUISINES,TIME,CITY,LOCALITY,RATING,VOTES,COST
129,None,9101,"North Indian, South Indian, Chinese, Continental","12noon – 3pm, 7pm – 2am (Mon-Sun)",NaN,NaN,3.6,728 votes,500
246,QUICK BITES,14502,Biryani,12noon – 11pm (Mon-Sun),NaN,Palarivattom Kochi,3.4,82 votes,300
411,None,6313,"North Indian, Chinese, Pizza, Burger, Fast Food",7pm – 4am (Mon-Sun),NaN,NaN,4.0,29 votes,600
466,None,1133,North Indian,4pm – 9pm (Mon-Sun),NaN,NaN,4.2,55 votes,200
481,None,4788,Street Food,"11am – 11pm (Mon),9:30am – 12midnight (Tue-Sun)",NaN,NaN,3.7,616 votes,250
...,...,...,...,...,...,...,...,...,...
12280,None,3446,"North Indian, Chinese",5pm – 5am (Mon-Sun),NaN,NaN,3.7,281 votes,500
12314,CASUAL DINING,11724,"North Indian, Bengali","11am – 3:30pm, 7pm – 11pm (Mon-Sun)",NaN,Opposite to corporation bank and LIC office ba...,4.3,775 votes,650
12447,QUICK BITES,7314,"North Indian, Chinese, Mughlai, Seafood",12:30pm – 12midnight (Mon-Sun),NaN,Hyderabad,3.1,44 votes,350
12567,None,15532,"Biryani, Chinese, Fast Food, North Indian","11am – 1am (Mon, Sun), 11am – 12:15AM (Tue-Sat)",NaN,NaN,3.7,656 votes,300
12615,None,13734,"Healthy Food, Salad",9am – 8pm (Mon-Sun),NaN,NaN,3.6,40 votes,400

In [74]:
df_train['TIME'].value_counts()

11am – 11pm (Mon-Sun)                                 1415
12noon – 12midnight (Mon-Sun)                          469
12noon – 11pm (Mon-Sun)                                407
11am – 12midnight (Mon-Sun)                            310
10am – 10pm (Mon-Sun)                                  221
                                                      ...
Closed (Mon),12:30pm – 4:30pm, 7:30pm – 10:30pm...       1
8am – 3:30am (Mon-Sun)                                   1
7am – 3:30pm, 4pm – 7pm, 7pm – 11pm (Mon-Sun)            1
9:30am – 10pm (Mon, Wed, Thu, Fri, Sat), 9am –...        1
5pm – 11:45pm (Mon),5pm – 11:45pm, 12midnight...         1
Name: TIME, Length: 2689, dtype: int64

Since the column time has too many unique values and values in different formats it cannot be used to gain any meaningful insights

### FEATURE ENGINEERING

In [75]:
d ={}
for i in df_train["CUISINES"].values:
    i = i.split(",")
    for j in i:
        j = j.strip()
        if j in d:
            d[j]+=1
        else:
            d[j]=1
len(d)

125

In [76]:
cuisines = d.keys()
for i in cuisines:
    df_train[i]=0
    df_test[i]=0
df_train

,TITLE,RESTAURANT_ID,CUISINES,TIME,CITY,LOCALITY,RATING,VOTES,COST,Malwani,...,Pakistani,Peruvian,Cuisine Varies,Irish,Multi Cuisine,Jewish,Vegan,Oriental,Modern Australian,Egyptian
0,CASUAL DINING,9438,"Malwani, Goan, North Indian","11am – 4pm, 7:30pm – 11:30pm (Mon-Sun)",Thane,Dombivali East,3.6,49 votes,1200,0,...,0,0,0,0,0,0,0,0,0,0
1,"CASUAL DINING,BAR",13198,"Asian, Modern Indian, Japanese",6pm – 11pm (Mon-Sun),Chennai,Ramapuram,4.2,30 votes,1500,0,...,0,0,0,0,0,0,0,0,0,0
2,CASUAL DINING,10915,"North Indian, Chinese, Biryani, Hyderabadi","11am – 3:30pm, 7pm – 11pm (Mon-Sun)",Chennai,Saligramam,3.8,221 votes,800,0,...,0,0,0,0,0,0,0,0,0,0
3,QUICK BITES,6346,"Tibetan, Chinese",11:30am – 1am (Mon-Sun),Mumbai,Bandra West,4.1,24 votes,800,0,...,0,0,0,0,0,0,0,0,0,0
4,DESSERT PARLOR,15387,Desserts,11am – 1am (Mon-Sun),Mumbai,Lower Parel,3.8,165 votes,300,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12685,QUICK BITES,13228,"North Indian, Burger, Kebab","12noon – 12midnight (Mon, Tue, Wed, Thu, Sun)...",Hyderabad,Gachibowli,3.8,546 votes,500,0,...,0,0,0,0,0,0,0,0,0,0
12686,"CASUAL DINING,BAR",9686,"Goan, Continental","12noon – 1am (Mon-Fri),11am – 5pm, 7pm – 1am...",Mumbai,Bandra Kurla Complex,4.3,1214 votes,1800,0,...,0,0,0,0,0,0,0,0,0,0
12687,LOUNGE,11133,"Finger Food, Continental, Asian, Chinese",12noon – 12:30AM (Mon-Sun),Navi Mumbai,Vashi,4.0,608 votes,1300,0,...,0,0,0,0,0,0,0,0,0,0
12688,CASUAL DINING,6134,"North Indian, South Indian, Chinese, Street Food",6am – 10:45pm (Mon-Sun),Chennai,Maduravoyal,3.5,32 votes,400,0,...,0,0,0,0,0,0,0,0,0,0
12689,CASUAL DINING,6430,"North Indian, Chinese",12:30pm – 11pm (Mon-Sun),Hyderabad,Vanasthalipuram,3.4,677 votes,600,0,...,0,0,0,0,0,0,0,0,0,0

In [77]:
def present(q,i):
    if i in q:
        return 1
    else:
        return 0

In [78]:
for i in cuisines:
    df_train[i] = df_train.apply(lambda row:present(row.CUISINES,i), axis = 1)
    df_test[i] = df_test.apply(lambda row:present(row.CUISINES,i), axis = 1)
df_train

,TITLE,RESTAURANT_ID,CUISINES,TIME,CITY,LOCALITY,RATING,VOTES,COST,Malwani,...,Pakistani,Peruvian,Cuisine Varies,Irish,Multi Cuisine,Jewish,Vegan,Oriental,Modern Australian,Egyptian
0,CASUAL DINING,9438,"Malwani, Goan, North Indian","11am – 4pm, 7:30pm – 11:30pm (Mon-Sun)",Thane,Dombivali East,3.6,49 votes,1200,1,...,0,0,0,0,0,0,0,0,0,0
1,"CASUAL DINING,BAR",13198,"Asian, Modern Indian, Japanese",6pm – 11pm (Mon-Sun),Chennai,Ramapuram,4.2,30 votes,1500,0,...,0,0,0,0,0,0,0,0,0,0
2,CASUAL DINING,10915,"North Indian, Chinese, Biryani, Hyderabadi","11am – 3:30pm, 7pm – 11pm (Mon-Sun)",Chennai,Saligramam,3.8,221 votes,800,0,...,0,0,0,0,0,0,0,0,0,0
3,QUICK BITES,6346,"Tibetan, Chinese",11:30am – 1am (Mon-Sun),Mumbai,Bandra West,4.1,24 votes,800,0,...,0,0,0,0,0,0,0,0,0,0
4,DESSERT PARLOR,15387,Desserts,11am – 1am (Mon-Sun),Mumbai,Lower Parel,3.8,165 votes,300,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12685,QUICK BITES,13228,"North Indian, Burger, Kebab","12noon – 12midnight (Mon, Tue, Wed, Thu, Sun)...",Hyderabad,Gachibowli,3.8,546 votes,500,0,...,0,0,0,0,0,0,0,0,0,0
12686,"CASUAL DINING,BAR",9686,"Goan, Continental","12noon – 1am (Mon-Fri),11am – 5pm, 7pm – 1am...",Mumbai,Bandra Kurla Complex,4.3,1214 votes,1800,0,...,0,0,0,0,0,0,0,0,0,0
12687,LOUNGE,11133,"Finger Food, Continental, Asian, Chinese",12noon – 12:30AM (Mon-Sun),Navi Mumbai,Vashi,4.0,608 votes,1300,0,...,0,0,0,0,0,0,0,0,0,0
12688,CASUAL DINING,6134,"North Indian, South Indian, Chinese, Street Food",6am – 10:45pm (Mon-Sun),Chennai,Maduravoyal,3.5,32 votes,400,0,...,0,0,0,0,0,0,0,0,0,0
12689,CASUAL DINING,6430,"North Indian, Chinese",12:30pm – 11pm (Mon-Sun),Hyderabad,Vanasthalipuram,3.4,677 votes,600,0,...,0,0,0,0,0,0,0,0,0,0

In [79]:
top_13_cities = df_train['CITY'].value_counts()[:13].index
top_13_cities

Index(['Chennai', 'Bangalore', 'Hyderabad', 'Mumbai', 'New Delhi', 'Kochi',
       'Gurgaon', 'Secunderabad', 'Noida', 'Navi Mumbai', 'Ghaziabad', 'Thane',
       'Faridabad'],
      dtype='object')

In [80]:
for i in top_13_cities:
    df_train[i]=0
    df_test[i]=0
df_train

,TITLE,RESTAURANT_ID,CUISINES,TIME,CITY,LOCALITY,RATING,VOTES,COST,Malwani,...,Mumbai,New Delhi,Kochi,Gurgaon,Secunderabad,Noida,Navi Mumbai,Ghaziabad,Thane,Faridabad
0,CASUAL DINING,9438,"Malwani, Goan, North Indian","11am – 4pm, 7:30pm – 11:30pm (Mon-Sun)",Thane,Dombivali East,3.6,49 votes,1200,1,...,0,0,0,0,0,0,0,0,0,0
1,"CASUAL DINING,BAR",13198,"Asian, Modern Indian, Japanese",6pm – 11pm (Mon-Sun),Chennai,Ramapuram,4.2,30 votes,1500,0,...,0,0,0,0,0,0,0,0,0,0
2,CASUAL DINING,10915,"North Indian, Chinese, Biryani, Hyderabadi","11am – 3:30pm, 7pm – 11pm (Mon-Sun)",Chennai,Saligramam,3.8,221 votes,800,0,...,0,0,0,0,0,0,0,0,0,0
3,QUICK BITES,6346,"Tibetan, Chinese",11:30am – 1am (Mon-Sun),Mumbai,Bandra West,4.1,24 votes,800,0,...,0,0,0,0,0,0,0,0,0,0
4,DESSERT PARLOR,15387,Desserts,11am – 1am (Mon-Sun),Mumbai,Lower Parel,3.8,165 votes,300,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12685,QUICK BITES,13228,"North Indian, Burger, Kebab","12noon – 12midnight (Mon, Tue, Wed, Thu, Sun)...",Hyderabad,Gachibowli,3.8,546 votes,500,0,...,0,0,0,0,0,0,0,0,0,0
12686,"CASUAL DINING,BAR",9686,"Goan, Continental","12noon – 1am (Mon-Fri),11am – 5pm, 7pm – 1am...",Mumbai,Bandra Kurla Complex,4.3,1214 votes,1800,0,...,0,0,0,0,0,0,0,0,0,0
12687,LOUNGE,11133,"Finger Food, Continental, Asian, Chinese",12noon – 12:30AM (Mon-Sun),Navi Mumbai,Vashi,4.0,608 votes,1300,0,...,0,0,0,0,0,0,0,0,0,0
12688,CASUAL DINING,6134,"North Indian, South Indian, Chinese, Street Food",6am – 10:45pm (Mon-Sun),Chennai,Maduravoyal,3.5,32 votes,400,0,...,0,0,0,0,0,0,0,0,0,0
12689,CASUAL DINING,6430,"North Indian, Chinese",12:30pm – 11pm (Mon-Sun),Hyderabad,Vanasthalipuram,3.4,677 votes,600,0,...,0,0,0,0,0,0,0,0,0,0

In [81]:
df_train['CITY'].fillna('Unknown',inplace=True)
df_test['CITY'].fillna('Unknown',inplace=True)

In [82]:
def present_city(q,i):
    if ((i in q) or (q in i)):
        return 1
    else:
        return 0

In [83]:
for i in top_13_cities:
    df_train[i] = df_train.apply(lambda row:present_city(row.CITY,i), axis = 1)
    df_test[i] = df_test.apply(lambda row:present_city(row.CITY,i), axis = 1)
df_train

,TITLE,RESTAURANT_ID,CUISINES,TIME,CITY,LOCALITY,RATING,VOTES,COST,Malwani,...,Mumbai,New Delhi,Kochi,Gurgaon,Secunderabad,Noida,Navi Mumbai,Ghaziabad,Thane,Faridabad
0,CASUAL DINING,9438,"Malwani, Goan, North Indian","11am – 4pm, 7:30pm – 11:30pm (Mon-Sun)",Thane,Dombivali East,3.6,49 votes,1200,1,...,0,0,0,0,0,0,0,0,1,0
1,"CASUAL DINING,BAR",13198,"Asian, Modern Indian, Japanese",6pm – 11pm (Mon-Sun),Chennai,Ramapuram,4.2,30 votes,1500,0,...,0,0,0,0,0,0,0,0,0,0
2,CASUAL DINING,10915,"North Indian, Chinese, Biryani, Hyderabadi","11am – 3:30pm, 7pm – 11pm (Mon-Sun)",Chennai,Saligramam,3.8,221 votes,800,0,...,0,0,0,0,0,0,0,0,0,0
3,QUICK BITES,6346,"Tibetan, Chinese",11:30am – 1am (Mon-Sun),Mumbai,Bandra West,4.1,24 votes,800,0,...,1,0,0,0,0,0,1,0,0,0
4,DESSERT PARLOR,15387,Desserts,11am – 1am (Mon-Sun),Mumbai,Lower Parel,3.8,165 votes,300,0,...,1,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12685,QUICK BITES,13228,"North Indian, Burger, Kebab","12noon – 12midnight (Mon, Tue, Wed, Thu, Sun)...",Hyderabad,Gachibowli,3.8,546 votes,500,0,...,0,0,0,0,0,0,0,0,0,0
12686,"CASUAL DINING,BAR",9686,"Goan, Continental","12noon – 1am (Mon-Fri),11am – 5pm, 7pm – 1am...",Mumbai,Bandra Kurla Complex,4.3,1214 votes,1800,0,...,1,0,0,0,0,0,1,0,0,0
12687,LOUNGE,11133,"Finger Food, Continental, Asian, Chinese",12noon – 12:30AM (Mon-Sun),Navi Mumbai,Vashi,4.0,608 votes,1300,0,...,1,0,0,0,0,0,1,0,0,0
12688,CASUAL DINING,6134,"North Indian, South Indian, Chinese, Street Food",6am – 10:45pm (Mon-Sun),Chennai,Maduravoyal,3.5,32 votes,400,0,...,0,0,0,0,0,0,0,0,0,0
12689,CASUAL DINING,6430,"North Indian, Chinese",12:30pm – 11pm (Mon-Sun),Hyderabad,Vanasthalipuram,3.4,677 votes,600,0,...,0,0,0,0,0,0,0,0,0,0

In [84]:
df_train['TITLE'].value_counts()[:15]

QUICK BITES           4218
CASUAL DINING         3652
None                  1003
CAFÉ                   607
DESSERT PARLOR         382
CASUAL DINING,BAR      349
FINE DINING            308
BAKERY                 302
BEVERAGE SHOP          156
BAR,CASUAL DINING      128
LOUNGE                  98
BAKERY,QUICK BITES      92
BAR                     91
FOOD COURT              78
CASUAL DINING,CAFÉ      56
Name: TITLE, dtype: int64

In [85]:
df_test['TITLE'].value_counts()[:15]

QUICK BITES           1416
CASUAL DINING         1258
None                   284
CAFÉ                   223
DESSERT PARLOR         126
CASUAL DINING,BAR      114
FINE DINING             98
BAKERY                  90
BEVERAGE SHOP           60
BAR,CASUAL DINING       47
LOUNGE                  38
BAKERY,QUICK BITES      34
BAR                     33
FOOD COURT              32
SWEET SHOP              23
Name: TITLE, dtype: int64

In [86]:
d1 ={}
for i in df_train["TITLE"].values:
    i = i.split(",")
    for j in i:
        j = j.strip()
        if j in d:
            d1[j]+=1
        else:
            d1[j]=1
d1

{'CASUAL DINING': 1,
 'BAR': 1,
 'QUICK BITES': 1,
 'DESSERT PARLOR': 1,
 'CAFÉ': 1,
 'MICROBREWERY': 1,
 'BEVERAGE SHOP': 1,
 'IRANI CAFE': 1,
 'BAKERY': 1,
 'None': 1,
 'PUB': 1,
 'FINE DINING': 1,
 'SWEET SHOP': 1,
 'LOUNGE': 1,
 'FOOD COURT': 1,
 'FOOD TRUCK': 1,
 'MESS': 1,
 'KIOSK': 1,
 'CLUB': 1,
 'CONFECTIONERY': 1,
 'DHABA': 1,
 'MEAT SHOP': 1,
 'COCKTAIL BAR': 1,
 'PAAN SHOP': 1}

In [87]:
title = d1.keys()
for i in title:
    df_train[i]=0
    df_test[i]=0
df_train

,TITLE,RESTAURANT_ID,CUISINES,TIME,CITY,LOCALITY,RATING,VOTES,COST,Malwani,...,FOOD COURT,FOOD TRUCK,MESS,KIOSK,CLUB,CONFECTIONERY,DHABA,MEAT SHOP,COCKTAIL BAR,PAAN SHOP
0,CASUAL DINING,9438,"Malwani, Goan, North Indian","11am – 4pm, 7:30pm – 11:30pm (Mon-Sun)",Thane,Dombivali East,3.6,49 votes,1200,1,...,0,0,0,0,0,0,0,0,0,0
1,"CASUAL DINING,BAR",13198,"Asian, Modern Indian, Japanese",6pm – 11pm (Mon-Sun),Chennai,Ramapuram,4.2,30 votes,1500,0,...,0,0,0,0,0,0,0,0,0,0
2,CASUAL DINING,10915,"North Indian, Chinese, Biryani, Hyderabadi","11am – 3:30pm, 7pm – 11pm (Mon-Sun)",Chennai,Saligramam,3.8,221 votes,800,0,...,0,0,0,0,0,0,0,0,0,0
3,QUICK BITES,6346,"Tibetan, Chinese",11:30am – 1am (Mon-Sun),Mumbai,Bandra West,4.1,24 votes,800,0,...,0,0,0,0,0,0,0,0,0,0
4,DESSERT PARLOR,15387,Desserts,11am – 1am (Mon-Sun),Mumbai,Lower Parel,3.8,165 votes,300,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12685,QUICK BITES,13228,"North Indian, Burger, Kebab","12noon – 12midnight (Mon, Tue, Wed, Thu, Sun)...",Hyderabad,Gachibowli,3.8,546 votes,500,0,...,0,0,0,0,0,0,0,0,0,0
12686,"CASUAL DINING,BAR",9686,"Goan, Continental","12noon – 1am (Mon-Fri),11am – 5pm, 7pm – 1am...",Mumbai,Bandra Kurla Complex,4.3,1214 votes,1800,0,...,0,0,0,0,0,0,0,0,0,0
12687,LOUNGE,11133,"Finger Food, Continental, Asian, Chinese",12noon – 12:30AM (Mon-Sun),Navi Mumbai,Vashi,4.0,608 votes,1300,0,...,0,0,0,0,0,0,0,0,0,0
12688,CASUAL DINING,6134,"North Indian, South Indian, Chinese, Street Food",6am – 10:45pm (Mon-Sun),Chennai,Maduravoyal,3.5,32 votes,400,0,...,0,0,0,0,0,0,0,0,0,0
12689,CASUAL DINING,6430,"North Indian, Chinese",12:30pm – 11pm (Mon-Sun),Hyderabad,Vanasthalipuram,3.4,677 votes,600,0,...,0,0,0,0,0,0,0,0,0,0

In [88]:
for i in title:
    df_train[i] = df_train.apply(lambda row:present(row.TITLE,i), axis = 1)
    df_test[i] = df_test.apply(lambda row:present(row.TITLE,i), axis = 1)
df_train

,TITLE,RESTAURANT_ID,CUISINES,TIME,CITY,LOCALITY,RATING,VOTES,COST,Malwani,...,FOOD COURT,FOOD TRUCK,MESS,KIOSK,CLUB,CONFECTIONERY,DHABA,MEAT SHOP,COCKTAIL BAR,PAAN SHOP
0,CASUAL DINING,9438,"Malwani, Goan, North Indian","11am – 4pm, 7:30pm – 11:30pm (Mon-Sun)",Thane,Dombivali East,3.6,49 votes,1200,1,...,0,0,0,0,0,0,0,0,0,0
1,"CASUAL DINING,BAR",13198,"Asian, Modern Indian, Japanese",6pm – 11pm (Mon-Sun),Chennai,Ramapuram,4.2,30 votes,1500,0,...,0,0,0,0,0,0,0,0,0,0
2,CASUAL DINING,10915,"North Indian, Chinese, Biryani, Hyderabadi","11am – 3:30pm, 7pm – 11pm (Mon-Sun)",Chennai,Saligramam,3.8,221 votes,800,0,...,0,0,0,0,0,0,0,0,0,0
3,QUICK BITES,6346,"Tibetan, Chinese",11:30am – 1am (Mon-Sun),Mumbai,Bandra West,4.1,24 votes,800,0,...,0,0,0,0,0,0,0,0,0,0
4,DESSERT PARLOR,15387,Desserts,11am – 1am (Mon-Sun),Mumbai,Lower Parel,3.8,165 votes,300,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12685,QUICK BITES,13228,"North Indian, Burger, Kebab","12noon – 12midnight (Mon, Tue, Wed, Thu, Sun)...",Hyderabad,Gachibowli,3.8,546 votes,500,0,...,0,0,0,0,0,0,0,0,0,0
12686,"CASUAL DINING,BAR",9686,"Goan, Continental","12noon – 1am (Mon-Fri),11am – 5pm, 7pm – 1am...",Mumbai,Bandra Kurla Complex,4.3,1214 votes,1800,0,...,0,0,0,0,0,0,0,0,0,0
12687,LOUNGE,11133,"Finger Food, Continental, Asian, Chinese",12noon – 12:30AM (Mon-Sun),Navi Mumbai,Vashi,4.0,608 votes,1300,0,...,0,0,0,0,0,0,0,0,0,0
12688,CASUAL DINING,6134,"North Indian, South Indian, Chinese, Street Food",6am – 10:45pm (Mon-Sun),Chennai,Maduravoyal,3.5,32 votes,400,0,...,0,0,0,0,0,0,0,0,0,0
12689,CASUAL DINING,6430,"North Indian, Chinese",12:30pm – 11pm (Mon-Sun),Hyderabad,Vanasthalipuram,3.4,677 votes,600,0,...,0,0,0,0,0,0,0,0,0,0

##### We can drop the TIME, CUISINES, CITY & LOCALITY  columns

In [ ]:
df_train.drop()